### ISSUE TITLE
Could not get unknown property 'sourceSets' ?

### ISSUE THREAD

**Issue by hrstoyanov** [WASdev/ci.gradle#169]
I bumped into a strange issue in Win7/64-bit that I do not see on MacOS using this pluging 2.0.1 and Gradle 4.3.1 and Java 8.  I think is is due to this plugin, but I am not sure. Any idea - here is the stacktrace from the build:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'sourceSets' for task ':recres-webapp:war' of type org.gradle.api.tasks.bundling.War.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at org.gradle.api.tasks.bundling.War_Decorated.getProperty(Unknown Source)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installLooseConfigWar(InstallAppsTask.groovy:156)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installLooseApplication(InstallAppsTask.groovy:139)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installProject(InstallAppsTask.groovy:120)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask$_installMultipleApps_closure1.doCall(InstallAppsTask.groovy:73)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installMultipleApps(InstallAppsTask.groovy:72)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installApps(InstallAppsTask.groovy:53)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

```

**Comment by jjvilleg** [comment]
Pull request #173  resolves the unknown property issue. I also switched some logic to look at the build/classes instead of serverDir to look for the compiled sources. This should take care of your issue. You can test these changes with our latest snapshot and we are planning on doing a point release sometime in the next week.

**Comment by hrstoyanov** [comment]
Thank you!
