### ISSUE TITLE
faces-initialization problem on JSF 2.3 and Liberty 18.0.0.3 with this plugin v2.6

### ISSUE THREAD

**Issue by nnworkspace** [WASdev/ci.gradle#286]
Dear developers!

I was trying to build a JSF 2.3 application on a locally installed OpenLiberty 18.0.0.3, and configured the server.xml following this guide:

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_jsf23.html

The local liberty started like a charm and my toy application also greeted a "hello world!" from the index.xhtml. So far so good.

Then I tried to build a CI/CD pipleline for my project, found this plugin and I was very happy. 

But strange enough, when I tried to start the same app on liberty with this gradle plugin, I always got this problem:
```
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/cwgenJsf/
[AUDIT   ] CWWKZ0001I: Application crossword-gen-jsf started in 4.607 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.3, servlet-4.0, beanValidation-2.0, jsf-2.3, cdi-2.0, localConnector-1.0, websocket-1.1, el-3.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
[ERROR   ] An error occured while initializing MyFaces: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [Faces Servlet] in application [crossword-gen-jsf]: java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure
 that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
A typical config looks like this;
<listener>
  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
</listener>

        at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:310)
        at [internal classes]

[ERROR   ] SRVE0276E: Error while initializing Servlet [Faces Servlet]: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:366)
        at [internal classes]
Caused by: java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure that you properly include all configuration settings necessary for a basic faces application and that all t
he necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
A typical config looks like this;
<listener>
  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
</listener>

        at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:310)
        ... 1 more

[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [Faces Servlet] in application [crossword-gen-jsf]: java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure
 that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
A typical config looks like this;
<listener>
  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
</listener>

        at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:310)
        at [internal classes]


```

Usually such problem occurs when there is lib-conflict. But I checked my build file and the produced war file, there isn't any library suspicious. I did not add another myfaces impl and I did not add any other jsf impl libs. 

More strange thing is, the same war can deploy and run without problem on my local liberty. Only problem when run with this plugin. 

My build file looks like this:
```
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'war'
apply plugin: 'liberty'

group 'org.ningning.sandbox'
version '0.0.1-SNAPSHOT'

sourceCompatibility = 1.8
targetCompatibility = 1.8
tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

// build script
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.6'
    }
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {

    compile 'com.google.guava:guava:27.0-jre'
    compile 'org.apache.commons:commons-math3:3.6.1'

    // JEE runtimes
    providedCompile group: 'javax', name: 'javaee-api', version: '8.0'
    providedCompile group: 'javax.faces', name: 'javax.faces-api', version: '2.3'
    providedCompile group: 'javax.servlet', name: 'javax.servlet-api', version:'4.0.1'

    //testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.3.1'
    testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.3.1'
    testCompile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.6'

    // The server
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[18.0.0.3,)'
}


test {
    useJUnitPlatform()
}

ext {
    appName = project.name
    testServerHttpPort = 9080
    testServerHttpsPort = 9443
    //warContext = appName
    warContext = 'cwgenJsf'
}

println '################## project path: ################'
println "Root project:   ${project.rootProject}"
println "  rootDir:      ${project.rootDir}"
println "  projectDir:   ${project.projectDir}"


// liberty server configs

liberty {
    server {
        //name = "${appName}Server"
        name = 'defaultServer'
        configFile = file("src/main/liberty/config/server.xml")
        bootstrapProperties = ['default.http.port': testServerHttpPort,
                               'default.https.port': testServerHttpsPort,
                               'app.context.root': warContext]
        packageLiberty {
            archive = "$buildDir/${appName}.zip"
            include = "usr"
        }
    }
}

war {
    archiveName = "${baseName}.${extension}"
}

test {
    reports.html.destination = file("$buildDir/reports/unit")
    reports.junitXml.destination = file("$buildDir/test-results/unit")
    exclude '**/it/**'
}

task integrationTest(type: Test) {
    group 'Verification'
    description 'Runs the integration tests.'
    reports.html.destination = file("$buildDir/reports/it")
    reports.junitXml.destination = file("$buildDir/test-results/it")
    include '**/it/**'
    exclude '**/unit/**'

    systemProperties = ['liberty.test.port': testServerHttpPort, 'war.name': warContext]
}

task openBrowser {
    description = 'Open browser to http://localhost:8080/${warContext}'
    doLast {
        java.awt.Desktop.desktop.browse "http://localhost:${testServerHttpPort}/${appName}".toURI()
    }
}

task openTestReport {
    description = 'Open browser to the test report'
    doLast {
        java.awt.Desktop.desktop.browse file("$buildDir/reports/it/index.html").toURI()
    }
}

clean.dependsOn 'libertyStop'
check.dependsOn 'integrationTest'
integrationTest.dependsOn 'libertyStart'
integrationTest.finalizedBy 'libertyStop'
integrationTest.finalizedBy 'openTestReport'
libertyPackage.dependsOn 'libertyStop'
```

And here is my server.xml:
```
<server description="Sample Servlet server">
  <!-- Enable features -->
  <featureManager>
    <feature>jsp-2.3</feature>
    <feature>servlet-4.0</feature>
    <feature>jsf-2.3</feature>
    <feature>el-3.0</feature>
    <feature>cdi-2.0</feature>
    <feature>localConnector-1.0</feature>
    <feature>beanValidation-2.0</feature>
    <feature>websocket-1.1</feature>
  </featureManager>

  <httpEndpoint httpPort="${default.http.port}" httpsPort="${default.https.port}"
    id="defaultHttpEndpoint" host="*"/>

  <!-- Automatically expand WAR files and EAR files -->
  <applicationManager autoExpand="true" />
  <applicationMonitor updateTrigger="mbean" />

  <webApplication id="crossword-gen-jsf" location="crossword-gen-jsf.war"
    contextRoot="${app.context.root}"/>
</server>
```

What am I doing wrong? Can anyone please help?
 
Here is the repository of my toy project (actually I even haven't started adding named beans yet...busy solving problems with server setup and the whole CI/CD plumbing files....), you can clone it and see if you can do a `grade libertyRun`  without the faces init problem:

https://github.com/nnworkspace/crossword-gen-jsf

Regards,
nn

**Comment by jjvilleg** [comment]
Hi, 

It looks like this is an issue with the looseApplication that is being generated. You can disable looseApplication as so while we continue to investigate. 
```
liberty {
    server {
        ...
        looseApplication = false
    }
}
```

**Comment by nnworkspace** [comment]
Yes, setting `looseApplication = false` really solved my problem! Thank you very much Juan!

**Comment by chyt** [comment]
We've just released version 2.6.1 of the plugin which implements the aforementioned workaround. If you upgrade to this version, you should be able to run your app successfully while still using `looseApplication = true`. Please try this out and let me know if it works for you.

**Comment by cherylking** [comment]
@nnworkspace Can you please let us know if version 2.6.1 resolves this issue for you?

**Comment by nnworkspace** [comment]
Hi hi, I'll verify it right away....

**Comment by nnworkspace** [comment]
yes, I modified my gradle build script as suggested by @chyt and tested the application. Yes, it works for me. Thank you all very much!
